### ISSUE TITLE
Count via query

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/lcsu#15]
https://github.com/ulsdevteam/lcsu/blob/fd1e3dc5a1307831f0275fafc29c4aa746a60f90/src/Controller/TraysController.php#L189-L192

Does this syntax work?

https://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#getting-a-count-of-results

**Comment by edensung25** [comment]
YES! It works perfectly. I applied on 0be6eeaa0237496a2d7169c29d8f42c501f9215f
