### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by bdgregg** [ulsdevteam/lcsu#18]
Suggestion: In the Users list change the column heading from "Permission Title" to "Role".

**Comment by edensung25** [comment]
update in commit 653dbe205e790a54e24ca7c68de041a966924557

**Comment by ctgraham** [comment]
Why was this line added in this commit?
https://github.com/ulsdevteam/lcsu/commit/653dbe205e790a54e24ca7c68de041a966924557#diff-434b377cd260c43f2728d4769386d1c4R12

**Comment by edensung25** [comment]
I remove the line which came from bin/cake. The default value(create_time) in database is CURRENT_TIMESTAMP. 408cb4bfb77a3b872d885cc3d0eb9b91d5196248

**Comment by ctgraham** [comment]
Ah, yes I misread the diff.  Resolved.
