### ISSUE TITLE
Verify a Tray - Status/Actions

### ISSUE THREAD

**Issue by bdgregg** [ulsdevteam/lcsu#20]
When "Verify a Tray", the Status and Actions are listed as "Validate".  This is a bit confusing.  The Status seems to be a button but is not.  Maybe the status should be "Needs Validation" instead of "Validate".  Remove the button look from the Status column if it will not actually be an action.

**Comment by edensung25** [comment]
update in commit d74c4db30ba7df426780e37f481c6b258f5abb67. The status are stored in status table, here is the [link](https://dev.voystaff.library.pitt.edu/lcsu/status)
