### ISSUE TITLE
Actions 

### ISSUE THREAD

**Issue by bdgregg** [ulsdevteam/lcsu#21]
Might I suggest that for any Actions that we make them to look like buttons so that the user knows that these are actions and not just words on the screen.  I understand the Actions Column, but it would be nice to see either buttons or vertical bars to separate more than one action.
ie. "View Edit" becomes: | View | Edit |

**Comment by edensung25** [comment]
update in the commit b09cf196a9baca72de11667d0e79f438a535d02c

**Comment by ctgraham** [comment]
@edensung25, this might have been more efficiently done with a CSS change, but this is fine for now.
