### ISSUE TITLE
Browse to Tray - Action add "Print Tray Label".

### ISSUE THREAD

**Issue by bdgregg** [ulsdevteam/lcsu#23]
When Browsing to a Tray, the actions are "View Export".  Can we add "Print Tray Label" as well to print just a single Tray label?

**Comment by ctgraham** [comment]
The "|" got captured in the link here:
https://github.com/ulsdevteam/lcsu/commit/eab22679aea2c93fde12801ed98ebcbe4e465dc2#diff-23680404cd78316a3fd637d4a2e139f8R12

This makes me like the pipes as action separators less.

**Comment by ctgraham** [comment]
Resolved.
