### ISSUE TITLE
"Incomplete Trays"

### ISSUE THREAD

**Issue by bdgregg** [ulsdevteam/lcsu#27]
What is the definition of an "Incomplete Tray"?  Does this mean it needs QC - Quality Control done which then I'd expect it should show under "Verify a Tray", or is it actually a partially filled tray that is not finished the initial scanning?  

If you review the tray that is incomplete, how would you know the total amount of books in the tray or are you starting from scratch here?  Maybe I didn't look far enough into this but I'm confused at this point.

**Comment by ctgraham** [comment]
This relates to #26.  Clarity with one issue or the other resolves both.

**Comment by bdgregg** [comment]
@ctgraham - Agreed Clarity is really what is needed.

**Comment by ctgraham** [comment]
Closing in favor of #26.
