### ISSUE TITLE
Adjust the permission for scanners

### ISSUE THREAD

**Issue by edensung25** [ulsdevteam/lcsu#30]
Remove management section from menu for scanners.

**Comment by edensung25** [comment]
Originally I set /ranges as homepage, but after removing the management section I think that the link should not be allowed for scanners. Thus, I set the homepage into /trays/init-scan instead, and restrict scanners can only access trays and books controllers.

**Comment by ctgraham** [comment]
The "Search" function should not be visible to scanners.
