### ISSUE TITLE
When re-scanning a tray, prompt whether to empty the tray

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/lcsu#42]
Staff should have input on the result of scanning a tray that is already in the scanning process.  For an incomplete tray, they may want to restart the scan or add an item.  For a "needs validation" tray, this should start the validation.  For a complete and/or exported tray, extra confirmation is needed if we are going to empty the existing tray.

**Comment by ctgraham** [comment]
This code forces a delete when scanning an incomplete tray:
https://github.com/ulsdevteam/lcsu/commit/75f732e07e8efd3a5a6f6b89d2d97407cdef2a74#diff-53bcb7439999e8c5d3fb34d7b4351003R164-R166

**Comment by ctgraham** [comment]
relates to https://github.com/ulsdevteam/lcsu/issues/41

**Comment by wopsononock** [comment]
fixed
