### ISSUE TITLE
Witnessed book scan which didn't proceed to completion

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/lcsu#44]
Entered 20 as a the scan count, scanned 20 books, though with multiple failures (repeat scanning, etc).  Never proceeded to the next Tray Barcode scan status.

**Comment by ctgraham** [comment]
R22-M06-S07-T14 is an example of this error.

**Comment by ctgraham** [comment]
R23-M12-S16-T12 is another example.

**Comment by ctgraham** [comment]
@nylorac , can you run another user test on this?

**Comment by nylorac** [comment]
@ctgraham Going to look into this now.

**Comment by nylorac** [comment]
I have tested this processs and scanning now proceedes to completion. I will have someone in LCSU do the verification a.s.a.p.

**Comment by ctgraham** [comment]
Thanks, @nylorac !  Looking forward to how Dave can break it.

**Comment by wopsononock** [comment]
tested successfully
