### ISSUE TITLE
Change display of list of items in a tray as unsorted

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/lcsu#49]
The list of items in a tray should be listed in scanned order, not in alphanumeric order.

**Comment by wopsononock** [comment]
Is this done?  I don't see a timestamp column here for example: http://dev.voystaff.library.pitt.edu/lcsu/trays/view/512740

**Comment by ctgraham** [comment]
No, the change https://github.com/ulsdevteam/lcsu/commit/4bf4795e0fcaef4beed6f0554f157255010e35aa targets the wrong list, but I see that the bug report wasn't clear.  This refers primarily to the tray verification process, but also is valid in the tray/view method.

The book pagination is using barcode as the order:
https://github.com/ulsdevteam/lcsu/blob/a0660c81226ceeba6ee4da05b6dfe4340a976941/src/Controller/TraysController.php#L54-L55
But should not.

There is no ordering in scanList method:
https://github.com/ulsdevteam/lcsu/blob/a0660c81226ceeba6ee4da05b6dfe4340a976941/src/Controller/TraysController.php#L395-L396
If this is not currently ordering in database-insert order, we may not be able to do this without adding a new column.

**Comment by wopsononock** [comment]
Fixed with Checked/Unchecked column in Validation module.
