### ISSUE TITLE
Verification step never completes

### ISSUE THREAD

**Issue by wopsononock** [ulsdevteam/lcsu#52]
When the number of matching scans reaches the number of books in the tray, the app does not kick off the action that prompts the user to scan the tray barcode -- a dead end.

**Comment by wopsononock** [comment]
It seems like the process must not ever get a true value for  line 44 of scan_list.ctp.  if (this.count == this.bookList.length) { ask for tray barcode scan...

**Comment by ctgraham** [comment]
Problem is here:
https://github.com/ulsdevteam/lcsu/blob/33a07c4e8220f4bfd4b63ec9252bbb0dffb03347/src/Template/Trays/scan_list.ctp#L42

The text was changed from "Uncheck" to "Unchecked" here:
https://github.com/ulsdevteam/lcsu/commit/c0034222f734dda7f127b52f14e5f1e26a361fa2#diff-712fbbadab25aac3297498e221ea37b9R73
but this instance was missed.

**Comment by ctgraham** [comment]
@nylorac , @wopsononock , this should be resolved.  Please verify.

**Comment by wopsononock** [comment]
This is working now.  Thank you Clinton!
