### ISSUE TITLE
Translate only the relevant output

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/lcsu#8]
https://github.com/ulsdevteam/lcsu/blob/fd1e3dc5a1307831f0275fafc29c4aa746a60f90/src/Controller/ModulesController.php#L140

should be:
`$this->Flash->success(__("Label: ").$shelf->shelf_barcode);`
because the shelf barcode is not subject to translation.

Also:
https://github.com/ulsdevteam/lcsu/blob/fd1e3dc5a1307831f0275fafc29c4aa746a60f90/src/Controller/ShelvesController.php#L157

https://github.com/ulsdevteam/lcsu/blob/fd1e3dc5a1307831f0275fafc29c4aa746a60f90/src/Controller/ShelvesController.php#L183

**Comment by ctgraham** [comment]
Why remove the successful print messages?  E.g. https://github.com/ulsdevteam/lcsu/commit/0be6eeaa0237496a2d7169c29d8f42c501f9215f#diff-256e16d0d4c91ba67f5da8aacec3bd74L183

**Comment by edensung25** [comment]
More changes are in 8e7644c31b90066dbf627d98f663b6374ae00bf0. About the successful print messages, I thought those messages will take to much spaces on the page. So I remove them. In the the commit 8e7644c31b90066dbf627d98f663b6374ae00bf0 , I use                 $this->Flash->success(__('All labels are printed out successfully.')); instead.

**Comment by ctgraham** [comment]
Resolved.
